
MYSQL_HOST=$(shell hostname -f)
MYSQL_PORT=3306
MYSQL_USER=admin
MYSQL_PASSWORD=Abcd1234
MYSQL_ROOT_PASSWORD=rootpass
TZ=Asia/Shanghai

DOCKER_IMAGE=mysql:8.4
SQL_PATH=../sql

BASENAME=$(shell basename "$(PWD)")
svc=primary
ct= $(svc)
#ct=$(BASENAME)_$(svc)
#ct=$(shell echo "${BASENAME}_${svc}")
# DOCKER_VOLUME=$(shell echo "${BASENAME}_${svc}_mysql_data")

export MYSQL_HOST MYSQL_PORT MYSQL_USER MYSQL_PASSWORD MYSQL_ROOT_PASSWORD TZ
export DOCKER_IMAGE SQL_PATH ct BASENAME svc