services:
  mysql_replica:
    image: mysql:8.4
    container_name: mysql_replica
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./replica.cnf:/etc/mysql/conf.d/replication.cnf
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysql_data:
