up:
	docker compose -f docker-compose.replica.yml up -d

down:
	docker compose -f docker-compose.replica.yml down

shell:
	docker compose -f docker-compose.replica.yml exec -it mysql_replica mysql -uroot -prootpass
