IMAGE_REPO=container-registry.oracle.com/mysql/community-router
TAG=8.4.1

MYSQL_HOST=10.1.1.105
MYSQL_PORT=3306
MYSQL_USER=root
MYSQL_PASSWORD=Abcd1234
MYSQL_INNODB_CLUSTER_MEMBERS=3
# MYSQL_ROUTER_BOOTSTRAP_EXTRA_OPTIONS="--conf-use-socket --conf-use-gr-notification"

export
