up:
	docker compose -f docker-compose.primary.yml up -d

down:
	docker compose -f docker-compose.primary.yml down

shell:
	docker compose -f docker-compose.primary.yml exec mysql_primary mysql -uroot -prootpass -hlocalhost
