version: '3'
services:
  app:
    image: "${REPO_PATH}${IMAGE}:${TAG}"
    #build: .
    env_file:
      - .env
    volumes:
      - ./app/:/app/
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
