services:
  mysql-a:
      container_name: mysql-a
      hostname: mysql-a
      image: mysql:8.4
      # build: .
      # command: --default-authentication-plugin=mysql_native_password
      environment:
        TZ: Asia/Shanghai
        MYSQL_ROOT_PASSWORD: Abcd1234
      ports:
        - "3306:3306"
        # - "33061:33061"
      volumes:
        - ./initdb.d/setup.sql:/docker-entrypoint-initdb.d/setup.sql
        - ./conf/my.cnf.a:/etc/mysql/my.cnf
        - ./data-mysql-a:/var/lib/mysql
      networks:
        - mysql-cluster
  
  mysql-b:
      container_name: mysql-b
      hostname: mysql-b
      image: mysql:8.4
      # build: .
      # command: --default-authentication-plugin=mysql_native_password
      environment:
        TZ: Asia/Shanghai
        MYSQL_ROOT_PASSWORD: Abcd1234
      ports:
        - "3307:3306"
        # - "33062:33062"
      volumes:
        - ./initdb.d/setup.sql:/docker-entrypoint-initdb.d/setup.sql
        - ./conf/my.cnf.b:/etc/mysql/my.cnf
        - ./data-mysql-b:/var/lib/mysql
      networks:
        - mysql-cluster
  
  mysql-c:
      container_name: mysql-c
      hostname: mysql-c
      image: mysql:8.4
      # build: .
      # command: --default-authentication-plugin=mysql_native_password
      environment:
        TZ: Asia/Shanghai
        MYSQL_ROOT_PASSWORD: Abcd1234
      ports:
        - "3308:3306"
        # - "33063:33063"
      volumes:
        - ./initdb.d/setup.sql:/docker-entrypoint-initdb.d/setup.sql
        - ./conf/my.cnf.c:/etc/mysql/my.cnf
        - ./data-mysql-c:/var/lib/mysql
      networks:
        - mysql-cluster

#   router0:
#       container_name: router0
#       hostname: router0
#       image: ${MYSQL_ROUTER_IMAGE}
#       environment:
#         MYSQL_HOST: ${MYSQL_HOST}
#         MYSQL_PORT: $(MYSQL_PORT)
#         MYSQL_USER: ${MYSQL_USER}
#         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#         MYSQL_INNODB_CLUSTER_MEMBERS: ${MYSQL_INNODB_CLUSTER_MEMBERS}
#       ports:
#         - "6446:6446"
#         - "6447:6447"
#         - "6448:6448"
#         - "6449:6449"
#         - "6450:6450"
#       depends_on:
#         - mysql-a
#         - mysql-b
#         - mysql-c
#       networks:
#         - mysql-cluster


networks:
  mysql-cluster:
    driver: bridge

volumes:
  data-mysql-a:
    driver: local
  data-mysql-b:
    driver: local
  data-mysql-c:
    driver: local
