services:
  mysql_replica:
    image: mysql:8.0.33
    container_name: mysql_replica
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./replica.cnf:/etc/mysql/conf.d/replication.cnf
    ports:
      - "3307:3306"
    restart: unless-stopped

volumes:
  mysql_data:
