services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./primary.cnf:/etc/mysql/conf.d/replication.cnf
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysql_data:
