services:
  primary:
    image: mysql:8.4
    container_name: mysql_primary
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./primary.cnf:/etc/mysql/conf.d/replication.cnf
    ports:
      - "3306:3306"
    restart: unless-stopped

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter
    command:
      - "--mysqld.username=exporter:Abcd1234"
      - "--mysqld.address=mysql:3306"
    ports:
      - "9104:9104"
    depends_on:
      - primary

volumes:
  mysql_data:
